
<html>
    <!--
     alae000.html
     Fecha creación: 07.jun.2013 (Rita de la Torre) Pantalla login del ALAE
     Modificación:
    -->
    <head>
        <title>ALAE</title>
        <style type="text/css" media="Screen"> /*\*/@import url("./css/alae.css");/**/ </style>
        <link rel="shortcut icon" href="img/favicon.ico">
    </head>
    <body>
        <div id="principal">
            <div id="cuerpo">
                <div id="izquierda">
                    <a href="alae000.html"><img src="./img/alaelogo.png"  title="volver a contenido" /></a>
                </div>
                <div id="derecha">
                    <h2>menu principal</h2>
                    <hr/>
                    <ul>
                        <li><a href="alae010.html">Analitos</a></li>
                        <li><a href="alae020.html">Estudios</a></li>
                        <li><a href="alae030.html">Estad&iacute;sticas</a></li>
                        <li><a href="alae040.html">Lotes sin asignar</a></li>
                        <li><a href="alae050.html">Administración de Usuarios (*)</a></li>
                        <li><a href="alae060.html">Parametrizaci&oacute;n (*)</a></li>
                        <!-- <li><a href="alae070.html">Mantenimiento Desplegables (*)</a></li> -->
                        <li><a target="_blank" href="http://www.tonymarston.net/php-mysql/auditlog.html">Audit Trail</a></li>
                        <li><a href="alae099.html">Salir de ALAE</a></li>
                    </ul>
                </div>
            </div>

            <div id="pie">
                <p><a href="./help/alae020.pdf" target="blank"><img src="./img/help.png"  title="ayuda sobre esta pantalla" /></a>
                    Usuario: <strong>Perfil</strong> | Fulanito de tal.</p>
                <p><a href="./sf/alae020sf.pdf" target="blank"><img src="./img/info.png"  title="Especificaciones funcionales" /></a>
                    ALAE Software. Copyright © Anapharm, 2013.</p>
            </div>
        </div>
    </body>
</html>