
<html>
    <!--
     alae000.html
     Fecha creación: 07.jun.2013 (Rita de la Torre) Pantalla login del ALAE
     Modificación:
    -->
    <head>
        <title>ALAE</title>
        <style type="text/css" media="Screen"> /*\*/@import url("./css/alae.css");/**/ </style>
        <link rel="shortcut icon" href="img/favicon.ico">
    </head>
    <body>
        <div id="principal">
            <div id="cuerpo">

                <div id="izquierda">
		    <img src="<?php echo $this->basePath() . '/img/alaelogo.png' ?> "  title="volver a contenido" />
                </div>
                <div id="derecha">
                    <h2>menu principal</h2>
                    <hr/>
                    <ul>
                        <li><a href="<?php echo $this->basePath() ?>/analyte/index">Analitos</a></li>
                        <li><a href="<?php echo $this->basePath() ?>/study/index">Estudios</a></li>
                        <li><a href="alae030.html">Estad&iacute;sticas</a></li>
                        <li><a href="<?php echo $this->basePath() ?>/batch/unfilled">Lotes sin asignar</a></li>
                        <li><a href="<?php echo $this->basePath() ?>/user/admin">Administración de Usuarios (*)</a></li>
                        <li><a href="<?php echo $this->basePath() ?>/parameter/index">Parametrizaci&oacute;n (*)</a></li>
                        <!-- <li><a href="alae070.html">Mantenimiento Desplegables (*)</a></li> -->
                        <li><a target="_blank" href="http://www.tonymarston.net/php-mysql/auditlog.html">Audit Trail</a></li>
                        <li><a href="<?php echo $this->basePath() ?>/index/logout">Salir de ALAE</a></li>
                    </ul>
                </div>
            </div>
	</div>
    </body>
</html>