<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php
	echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	<!-- Le styles -->
	<?php
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/alae.css')
		->prependStylesheet($this->basePath() . '/css/datatable.css')
	?>
	<!-- Scripts -->
	<?php
	echo $this->headScript()
		->prependFile($this->basePath() . '/js/script.js')
		->prependFile($this->basePath() . '/js/additional-methods.min.js')
		->prependFile($this->basePath() . '/js/jquery.validate.min.js')
		->prependFile($this->basePath() . '/js/jquery.js')
		->prependFile($this->basePath() . '/public/css/style.css');
	?>
	<script>
	    var basePath = '<?php echo $this->basePath() ?>';
        </script>
        <script src="http://yui.yahooapis.com/3.14.0/build/yui/yui-min.js"></script>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
        <style>
            span, a{ margin-right: 5px; }
            .form-datatable-remove{ display:none; }
            .clone .form-datatable-add{ display:none; }
            .clone .form-datatable-remove{ display:block; }
        </style>
    </head>
    <body>
	<div class="container">
	    <?php echo $this->content; ?>

	    <div id="pie">

		<?php echo Alae\Service\Helper::getUserSession(); ?>
		<p><a href="./sf/alae020sf.pdf" target="blank"><img src="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/img/info.png' ?>"  title="Especificaciones funcionales" /></a>
                    ALAE Software. Copyright © Anapharm, 2013.</p>
            </div>




	</div>
    </body>
</html>



