<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>
            footer {
            position:fixed; 
            bottom:0; 
            left:0; 
            background:#eee;; 
            height:50px; 
            width:100%;
        }
        </style>
	<?php echo $this->headTitle('ALAE')->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php
	echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	<!-- Le styles -->
	<?php
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/alae.css')
		->prependStylesheet($this->basePath() . '/css/datatable.css')
		->prependStylesheet($this->basePath() . '/css/reports.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
	?>
	<!-- Scripts -->
	<?php
	echo $this->headScript()
		->prependFile($this->basePath() . '/js/script.js')
		->prependFile($this->basePath() . '/js/additional-methods.min.js')
		->prependFile($this->basePath() . '/js/jquery.validate.min.js')
		->prependFile($this->basePath() . '/js/jquery.js')
		->prependFile($this->basePath() . '/js/yui.min.js')
		//->prependFile($this->basePath() . '/public/css/style.css');
	?>
	<script>
	    var basePath = '<?php echo $this->basePath() ?>';
        </script>

        <script src="http://yui.yahooapis.com/3.14.0/build/yui/yui-min.js"></script>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
        
        <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script src="http://malsup.github.com/jquery.form.js"></script>
        
        <script>
            function Verificar()
            {
                var tecla=window.event.keyCode;
                if (tecla==116) { event.keyCode=0;
                event.returnValue=false;}
            
                if(event.ctrlKey) {
		//Bloquear Ctrl
                event.keyCode=0;
                event.returnValue=false;
                }
            }
        </script>
    </head>
    <body onKeyDown="javascript:Verificar()">
        <div id="container" style="margin-bottom:70px;">
	    <?php echo $this->content; ?>	    
	</div>
        <footer>
            <p>
                <?php echo Alae\Service\Helper::getUserSession(); ?>&nbsp;ALAE Software. Copyright © Anapharm Europe, V.1.0 <?php echo "16-06-2014"; ?>
            </p>
        </footer>
        <?php if (Alae\Service\Helper::getUserSession()) : ?>
            <script>
            var close;
            $(document).on('mousemove', function(e){
                clearTimeout(close);
                closeSession();
            });
            window.onload = function()
            {
                closeSession();
            }

            function closeSession()
            {
                close = setTimeout("window.location.href = '" + basePath + "/index/logout';",900000);
            }
            </script>
        <?php endif; ?>
    </body>
</html>



