<form id="datatable-form" action="#" method="POST">
    <div id="datatable"></div>
</form>
<script>$("#datatable-form").validate();</script>
<script>
    var createNumberIncr = 0;
    var data = <?php echo $data; ?>;
    var filters = <?php echo $filters; ?>;
    var columns = <?php echo $columns; ?>;
    var editable = <?php echo $editable; ?>;
    var excel = basePath + '/analyte/excel';
    var pdf = basePath + '/analyte/pdf';
    var deleteUrl = basePath + '/analyte/delete';
</script>
<script type="text/javascript" src="/alae/public/js/datatable.js"></script>