<form id="datatable-form" action="#" method="POST">
    <div id="datatable"></div>
</form>
<script>
    jQuery.validator.addClassRules('datatable-class-name', {
        required: true
    });
    jQuery.validator.addClassRules('datatable-class-shortname', {
        required: true
    });
    $("#datatable-form").validate();
</script>
<script>
    var createNumberIncr = 0;
    var data = <?php echo $data; ?>;
    var filters = <?php echo $header; ?>;
    var columns = <?php echo $columns; ?>;
    var editable = <?php echo $editable; ?>;
    var deleteUrl = basePath + '/analyte/delete';
    var filtersHtml = '<?php echo $filters; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/js/datatable.js"></script>