
        <script src="http://code.highcharts.com/highcharts.js"></script>
        <script src="http://code.highcharts.com/modules/exporting.js"></script>

        <div id="graphics" style="height: 400px; margin-top: 1em"></div>
        <button id="button">Export chart</button>

        <script>
        $(function () {
            var chart = $('#graphics').highcharts({
                chart: {
                    type: 'scatter',
                    zoomType: 'xy'
                },
                title: {
                    text: 'Height Versus Weight of 507 Individuals by Gender'
                },
                exporting: {
                    buttons: {
                        contextButton: {
                            menuItems: null,
                            onclick: function() {
                                this.exportChart({type: 'application/pdf',
                                filename: 'my-pdf'});

                            }
                        }
                    }
                },
                subtitle: {
                    text: 'Source: Heinz  2003'
                },
                xAxis: {
                    startOnTick: true,
                    endOnTick: true,
                    showLastLabel: true
                },
                yAxis: {
                    title: {
                        text: 'Weight (kg)'
                    }
                },
                legend: {
                    borderRadius: 0,
                    itemDistance: 20
                },
                plotOptions: {
                    scatter: {
                        marker: {
                            radius: 5,
                            states: {
                                hover: {
                                    enabled: true,
                                    lineColor: 'rgb(100,100,100)'
                                }
                            }
                        },
                        states: {
                            hover: {
                                marker: {
                                    enabled: false
                                }
                            }
                        }
                    }
                },
                tooltip: {
                    headerFormat: '<b>{series.name}</b><br>',
                    pointFormat: 'IS Peak Area: {point.y}'
                },
                series: [{
                    name: 'Muestras',
                    color: '#007ca5',
                    data: [2877032,3027176,2965433,2777772,2573473,2843870,2775022,2799750,2663891,2697619,
                       2596812,2565242,2700659,2762870,2663472,2667739,2568367,2618185,2983085,2806734,2386133,
                       2494967,2500897,2518464,2621355,2594352,2600603,2639183,2674769,2574755,2661117,2544129,
                       2698694,2689866,2587778,2625737,2836369,2795772,2727723,2686046,2664310,2722799,2789913,
                       2647964,2740253,2774768,2753381,2693802,2748398,2743749,2654807,2603908,2624185,2508829,
                       2762118,2652786,2766278,2687468,2732369,2766275,2819963,2514581,2674405,2683406,2679938,
                       2502042,2567820,2562452,2605332,2525821,2520713,2482382]

                }, {
                    name: 'CS/QC',
                    color: '#F86611',
                    data: [2991603,2453877,3018175,2581239,2851983,2722431,2834600,2465936,2814323,2549752,2850770,
                        2525448,2762375,2459240,2778502,2324079,2712802,2479736,2659504,2533761,2573083,2592267,
                        2788838,2611042]
                },{
                    name: 'Promedio',
                    type: 'line',
                    color: '#0d233a',
                    marker: {
                        enabled: false,
                        states: {
                            hover: {
                                enabled: true
                            }
                        }
                    },
                    data: [2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,
                        2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,
                        2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,
                        2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,
                        2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,
                        2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,2663974,
                        2663974,2663974,2663974,2663974,2663974,2663974]
                }]
            });


            $('#button').click(function() {
        var chart = $('#graphics').highcharts();
        chart.exportChart({type: 'application/pdf',
                                filename: 'my-pdf'});
    });



        });
        </script>