<div id="principal">
    <div id="logo">
        <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
    </div>
    <div id="cerrar">
        [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/index/menu' ?>">regresar al menú</a>]
    </div>
    <div id="cuerpo">
        <div id="encab">
            <h2>informes estad&iacute;sticos</h2>
        </div>
        <div id="centrado" style="font-size:1em;">
            <p>
                <label>C&oacute;digo del Estudio:</label>
                <select id="study">
		    <?php foreach ($studies as $study) : ?>
    		    <option value="<?php echo $study->getPkStudy(); ?>"><?php echo $study->getCode(); ?></option>
		    <?php endforeach; ?>
                </select>
            </p>
            <p id="ajax" style="display: none">
                <label>Analito (*): </label>
                <select id="analyte"></select>
            </p>
            <h4>Seleccione el informe deseado:</h4>
            <ul class="pdf"><br/>
                <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r1', false);">01. Información General de un Estudio</a></li>
                <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r2', false);">02. Resumen de Lotes de un Estudio</a></li>
                <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r3', true);">03. Listado de Muestras a Repetir (*)</a></li>
            </ul>
            <ul class="xls">
                <li><a href="alae0304.xlsx" target="_blank">04. Summary of Calibration Curve Parameters (*)</a></li>
                <li><a href="alae0305.xlsx" target="_blank">05. Back-Calculated Concentration of Calibration Standard (*)</a></li>
                <li><a href="alae0306.xlsx" target="_blank">06. Calculated % Nominal Concentration of Calibration Standards (*)</a></li>
                <li><a href="alae0307.xlsx" target="_blank">07. Between-Run Accuracy and Precision of Quality Control Samples (*)</a></li>
                <li><a href="alae0308.xlsx" target="_blank">08. Between-Run Accuracy and Precision of Dilution Quality Control Samples (*)</a></li>
            </ul>
        </div>
    </div>
    <blockquote class="peq">
        Los reportes con (*) requieren que se seleccione un Analito de la lista deplegable <strong>Analito (*)</strong>
    </blockquote>
</div>
<script>
    function reports(url, isAnalyte)
    {
        var isRedirect = true;
	url = url + "?id=" + $("#study").val();
	if (isAnalyte && $("#analyte").val() !== null)
	{
	    url = url + "&an=" + $("#analyte").val();
	}
        else
        {
            alert("Debe seleccionar un Analito");
            isRedirect = false;
        }

        if(isRedirect)
        {
            window.location = url;
        }
    }

    $('#study').on('change', function() {
	var optionSelected = $("option:selected", this);
	var id = this.value;
	$.ajax
        ({
            type: "GET",
            dataType: "json",
            url: basePath + "/report/ajax",
            data: {id: id},
            success: function(data)
            {
                $('#analyte').html(data.data);
                $('#ajax').show();
                $('#analyte').show();
            }
        });
    });
</script>
