<?php

/*

  header('Content-Disposition: attachment; filename="' . $filename . '.xls";');
  header('Content-Type: application/vnd.ms-excel');
  ob_start();
 *
 */
?>
<page format="432x240" orientation="L" backcolor="#FFFFFF" style="font: arial;">
    <div class="table-container">
	<table width="600" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;">
	    <tr>
		<td colspan="20">
		    <h3>ALAE_BATCH RESULTS TABLE</h3>
		</td>
	    </tr>
	    <tr>
		<td width="200" colspan="5" align="left" height="20"  style="font-size: 11px;font-weight: bold;">
		    Código del estudio:
		</td>
		<td width="200" colspan="5" align="left"  height="20" style="">
		    !!!!!! echo $batch->getFkStudy()->getCode(); ??????
		</td>
		<td width="200" colspan="5" align="left"  style="font-size: 11px;font-weight: bold;">
		    Calibration Curve Parameters (Y= mX+b)
		</td>
		<td width="200" colspan="5" align="left"  height="20">
		</td>
	    </tr>
	    <tr>
		<td  colspan="5" align="left" height="20"   style="font-size: 11px;font-weight: bold;">
		    Analito:
		</td>
		<td  align="left" colspan="5" height="20" style="">
		    !!!!!! echo $batch->getFkAnalyte()->getName(); ??????
		</td>
		<td   colspan="5"  height="20"  align="left" style="font-size: 11px;font-weight: bold;">
		    m=
		</td>
			<td  colspan="5" align="left"  height="20"></td>
	    </tr>
	    <tr>
		<td  colspan="5" align="left" height="20"   style="font-size: 11px;font-weight: bold;">
		    Nombre del archivo exportado:
		</td>
		<td width="200" colspan="5" height="20" align="left" style="">
		    !!!!!! echo $batch->getFileName(); ??????
		</td>
		<td  colspan="5" align="left" height="20"   style="font-size: 11px;font-weight: bold">
		    x=
		</td>
		<td  colspan="5" align="left"  height="20">
		</td>
	    </tr>
	    <tr>
		<td  colspan="5" align="left" height="20"   style="font-size: 11px;font-weight: bold">
		    Fecha de importación:
		</td>
		<td  colspan="5" height="20" align="left" style="">
		    !!!!!! echo $batch->getCreatedAt(); ??????
		</td>
		<td  colspan="5" align="left"  height="20"   style="font-size: 11px;font-weight: bold;font-weight: bold">
		    r=
		</td>
		<td   colspan="5" align="left"  height="20">
		</td>
	    </tr>
	    <tr>
		<td colspan="20"></td>
	    </tr>
	    <tr>
		<td colspan="5" align="left" height="20"   style="font-size: 11px;font-weight: bold">
		    Resultado de la Evaluación:
		</td>
		<td colspan="5" height="20" style="">
		    !!!!!! echo $batch->getValidFlag(); ??????
		</td>
		<td  colspan="5" align="left"  height="20"  align="center" style="font-size: 11px;font-weight: bold">
		    Motivo de Rechazo:
		</td>
		<td  colspan="5" align="left"  height="20">
		    !!!!!! echo $error; ??????
		</td>
	    </tr>
	    <tr>
		<td colspan="10" align="left" height="20"  align="center" style="font-size: 11px;font-weight: bold;">
		    Usuario:
		</td>
		<td  colspan="10" align="left" height="20" style="">
		    !!!!!! echo $batch->getFkUser()->getUsername(); ??????
		</td>
	    </tr>
	    <tr>
		<td width="200" colspan="10" align="left" height="20"  align="left" style="font-size: 11px;font-weight: bold;">
		    Fecha de la Evaluación:
		</td>
		<td width="200" colspan="10" align="left"  height="20" style="">
		    !!!!!! echo $batch->getValidationDate(); ??????
		</td>
	    </tr>
		<tr>
			<td align="center"   style="color:#000; border: black 1px solid;font-size:11px;padding:4px">Sample Name</td>
			<td align="center"  style=" border: black 1px solid;font-size:11px;padding:4px">Analyte peak name</td>
			<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Sample Type</td>
			<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px"> File name </td>
			<td align="center"   style="color:#000; border: black 1px solid;font-size:11px;padding:4px">Analyte peak</td>
			<td align="center"  style=" border: black 1px solid;font-size:11px;padding:4px">IS peak name</td>
			<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Area ratio</td>
			<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px"> Analyte concentration</td>
			<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Dilution factor</td>
			<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px"> Accuracy</td>
			<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Use record</td>
	    </tr>
	    !!!!!! foreach ($elements as $SampleBatch) : ??????
	    <tr>
		<td align="center"   style="color:#000; border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getSampleName() ;??????
		</td>
		<td align="center"  style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getAnalytePeakName() ;??????
		</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getSampleType() ;??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getFileName() ;??????
		</td>
		<td align="center"   style="color:#000; border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getAnalytePeakArea() ;??????
		</td>
		<td align="center"  style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getIsPeakName() ;??????
		</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getIsPeakArea() ;??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getAnalyteConcentration() ;??????
		</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getDilutionFactor() ;??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getAccuracy() ;??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $SampleBatch->getUseRecord() ;??????
		</td>
	    </tr>
	    !!!!!! endforeach; ??????
	    <tr>
		<td colspan="20" align="left">Fecha y hora de impresión</td>
	    </tr>

	    <tr>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Sample name</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Acquisition date</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Analyte integration type</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">IS integration type</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Record modified </td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Rejection Reason</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">Message</td>
	    </tr>
	    !!!!!! foreach ($list as $data) : ??????
	    <tr>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $data["sample_name"]; ??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $data["acquisition_date"]; ??????
		</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $data["analyte_integration_type"]; ??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $data["is_integration_type"]; ??????
		</td>
		<td align="center"   style="border: black 1px solid;;font-size:11px;padding:4px">
		    !!!!!! echo $data["record_modify"]; ??????
		</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $data["rejection_reason"]; ??????
		</td>
		<td align="center"   style=" border: black 1px solid;font-size:11px;padding:4px">
		    !!!!!! echo $data["message"]; ??????
		</td>
	    </tr>
	    !!!!!! endforeach; ??????
	    <tr>
		<td colspan="20" align="right">Fecha y hora de impresión</td>
	    </tr>
	</table>
    </div>

</page>
<?php

$content = ob_get_clean();
// convert to PDF
require_once dirname(__FILE__) . "/html2pdf/html2pdf.class.php";
$filename = sprintf('%s.pdf', rawurlencode(preg_replace('~&#(\d{3,8});~e', '$fixchar(\'$1\')', $_REQUEST['name'])));
try
{
    $html2pdf = new HTML2PDF('P', array(432, 240), 'en', true, 'UTF-8', array(0, 0, 0, 0));
    $html2pdf->setDefaultFont('Arial');
    $html2pdf->writeHTML($content);
    $html2pdf->Output($filename . ".pdf", 'D');
}
catch (HTML2PDF_exception $e)
{
    echo $e;
}
exit;
?>