<nobreak>
<div class="table-container">
    <table width="600" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding:100px;font: arial;">
        <tr>
            <td colspan="20">
                <h3>TABLA DE RESULTADOS ALAE</h3>
            </td>
        </tr>
        <tr>
            <td width="200" colspan="2" align="left" height="20"  style="font-size: 13px;font-weight: bold;">
                Código del estudio:
            </td>
            <td width="200" colspan="2" align="left"  height="20" style="">
                <?php echo $batch->getFkStudy()->getCode(); ?>
            </td>
            <td width="200" colspan="2" align="left"  style="font-size: 13px;font-weight: bold;">
                Parámetros de la Curva de Calibrado (Y= mX+b)
            </td>
            <td width="200" colspan="2" align="left"  height="20">
            </td>
        </tr>
        <tr>
            <td  colspan="2" align="left" height="20"   style="font-size: 13px;font-weight: bold;">
                Analito:
            </td>
            <td  align="left" colspan="2" height="20" style="">
                <?php echo $batch->getFkAnalyte()->getName(); ?>
            </td>
            <td   colspan="2"  height="20"  align="left" style="font-size: 13px;font-weight: bold;">
                m=
            </td>
            <td  colspan="2" align="left"  height="20">
            <?php echo Alae\Service\Helper::getformatDecimal($batch->getSlope()); ?>                
            </td>
        </tr>
        <tr>
            <td  colspan="2" align="left" height="20"   style="font-size: 13px;font-weight: bold;">
                Nombre del archivo exportado:
            </td>
            <td width="200" colspan="2" height="20" align="left" style="">
                <?php echo $batch->getFileName(); ?>
            </td>
            <td  colspan="2" align="left" height="20"   style="font-size: 13px;font-weight: bold">
                x=
            </td>
            <td  colspan="2" align="left"  height="20">
            <?php echo Alae\Service\Helper::getformatDecimal($batch->getIntercept()); ?>
            </td>
        </tr>
        <tr>
            <td  colspan="2" align="left" height="20"   style="font-size: 13px;font-weight: bold">
                Fecha de importación:
            </td>
            <td  colspan="2" height="20" align="left" style="">
                <?php echo $batch->getCreatedAt(); ?>
            </td>
            <td  colspan="2" align="left"  height="20"   style="font-size: 13px;font-weight: bold;font-weight: bold">
                r=
            </td>
            <td   colspan="2" align="left"  height="20">
                <?php echo $batch->getCorrelationCoefficient(); ?>
            </td>
        </tr>
        <tr>
            <td colspan="20"></td>
        </tr>
        <tr>
            <td colspan="2" align="left" height="20"   style="font-size: 13px;font-weight: bold">
                Resultado de la Evaluación:
            </td>
            <td colspan="2" height="20" style="">
                <?php echo $batch->getValidFlag() ? "ACEPTADO" : "RECHAZADO"; ?>
            </td>
            <td  colspan="2" align="left"  height="20"  align="center" style="font-size: 13px;font-weight: bold">
                Motivo de Rechazo:
            </td>
            <td  colspan="2" align="left"  height="20">
                <?php echo $errors; ?>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="left" height="20"  align="center" style="font-size: 13px;font-weight: bold;">
                Usuario:
            </td>
            <td  colspan="2" align="left" height="20" style="">
                <?php echo $batch->getFkUser()->getUsername(); ?>
            </td>
        </tr>
        <tr>
            <td width="200" colspan="2" align="left" height="20"  align="left" style="font-size: 13px;font-weight: bold;">
                Fecha de la Evaluación:
            </td>
            <td width="200" colspan="2" align="left"  height="20" style="">
                <?php echo $batch->getValidationDate(); ?>
            </td>
        </tr>
        <tr>
            <td align="center"   style="color:#000; border: black 1px solid;font-size:13px;padding:4px">Sample Name</td>
            <td align="center"  style=" border: black 1px solid;font-size:13px;padding:4px">Analyte peak name</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Sample Type</td>
            <td align="center"   style="border: black 1px solid;;font-size:13px;padding:4px"> File name </td>
            <td align="center"   style="color:#000; border: black 1px solid;font-size:13px;padding:4px">Analyte peak area</td>

            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">IS peak area</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Area ratio</td>
            <td align="center"   style="border: black 1px solid;;font-size:13px;padding:4px"> Analyte concentration</td>
            <td align="center"   style="border: black 1px solid;;font-size:13px;padding:4px"> Calculated concentration</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Dilution factor</td>
            <td align="center"   style="border: black 1px solid;;font-size:13px;padding:4px"> Accuracy</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Use record</td>
        </tr>
        <?php echo $tr1; ?>
        <tr>
            <td colspan="20" align="right">&nbsp;</td>
        </tr>
        <tr>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Sample name</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Acquisition date</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Analyte integration type</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">IS integration type</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Record modified </td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Rejection Reason</td>
            <td align="center"   style=" border: black 1px solid;font-size:13px;padding:4px">Message</td>
        </tr>
        <?php echo $tr2; ?>
        <tr>
            <td colspan="20" align="right">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="20" align="right">Fecha y hora de impresión: <?php echo date("d.m.Y H:i"); ?></td>
        </tr>
    </table>
</div>
</nobreak>