<?php
//header('Content-Disposition: attachment; filename="prueba.xls";');
//header('Content-Type: application/vnd.ms-excel');
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
	<div class="table-container">
	    <h3>RESUMEN DE LOTES DE UN ESTUDIO </h3>
	    <table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding: 4px;font-size:11px;">
		<tr>
		    <td width="238" align="left" height="20" bgcolor="#000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
			Código del estudio:
		    </td>
		    <td width="205" height="20" style="border: black 1px solid;padding: 4px;">

		    </td>
		    <td width="273" height="20" bgcolor="#000" style="border: black 1px solid;color:#F1DADA;padding: 4px">
			Analito

		    </td>
		    <td width="174" align="center" height="20" style="border: black 1px solid;">

		    </td>

		</tr>
	    </table>
	    <div class="table-row">


		<table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff,margin-top:10px;font-size:11px;">
		    <tr>
			<td width="238" align="left" height="20" bgcolor="#000" style="border: black 1px solid;color:#97C1DA;padding:4px;font-size:11px;">
			    Identificación de la muestra
			</td>
			<td width="238" align="left" height="20" bgcolor="#000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
			    Evaluación
			    ( Aceptado / Rechazado )
			</td>
			<td width="238" align="left" height="20" bgcolor="#000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
			    Motivo
			    ( En caso de ser Rechazado )
			</td>



		    </tr>
		    <tr>

			<td width="238" align="left" height="20" bgcolor="#B7CCE3" style="border: black 1px solid;padding:4px;">

			</td>
			<td width="238" align="left" height="20" bgcolor="#B7CCE3" style="border: black 1px solid;padding:4px;">

			</td>
			<td width="238" align="left" height="20" bgcolor="#F1DADA" style="border: black 1px solid;padding:4px;">

			</td>


		    </tr>
		    <tr>
			<td  align="right" height="20" colspan="3">
			    Fecha de la Evaluación:

			</td>


		</table>
	    </div>
    </body>
</html>
