<?php
//header('Content-Disposition: attachment; filename="prueba.xls";');
//header('Content-Type: application/vnd.ms-excel');
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
	<div class="table-container">

	    <table width="890" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding:10px 0 0 0;">
		<tr>
		    <td width="238" align="left" height="20">

			Study No:
		    </td>
		    <td width="205" height="20" style="">

		    </td>


		</tr>
		<tr>
		    <td width="238" align="left" height="20"  align="center" style="padding:10px 0 0 0;">
			Table
		    </td>
		</tr>
		<tr>

		    <td width="238" colspan="2" align="left" height="20"  style="padding:10px 0 0 0;">
			<strong>Summary of Calibration Curve Parameters</strong>
		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 0 0 0">

			Analyte:
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 00 0">

			Biological Matrix
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>
	    </table>

	    <div class="cler"></div>
	    <div class="table-row">

		<table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff,margin-top:10px;text-aling:center;">
		    <tr>
			<td  colspan="4" align="center"></td>
		    </tr>
		    <tr>
			<td  align="center"   style="color:#000; border: black 1px solid;font-size:11px;padding:10px">Batch Results Table No. </td>
			<td  align="center"  style=" border: black 1px solid;font-size:11px;padding:10px">Slope (m)</td>
			<td  align="center"   style=" border: black 1px solid;font-size:11px;padding:10px">Y-Intercept (b)</td>
			<td align="center"   style="border: black 1px solid;font-size:11px;padding:10px"> CorrelationCoefficient ( r ) </td>


		    </tr>
		    <tr>

			<td align="center"  height="20px" bgcolor="#B7CCE3" style="color:#000; border: black 1px solid;font-size:11px;padding:4px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;font-size:11px;padding:4px"></td>
			<td  align="center"   bgcolor="#B7CCE3"  style=" border: black 1px solid;font-size:11px;padding:4px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style="border: black 1px solid;;font-size:11px;padding:4px"> </td>

		    </tr>
		    <tr>

			<td align="center"  height="20px" style="color:#000; border: black 1px solid;font-size:11px;padding:4px"></td>
			<td  align="center"  style=" border: black 1px solid;font-size:11px;padding:4px"></td>
			<td  align="center"    style=" border: black 1px solid;font-size:11px;padding:4px"></td>
			<td  align="center"   style="border: black 1px solid;;font-size:11px;padding:4px"> </td>

		    </tr>
		    <tr>
			<td colspan="4" align="left" style="padding: 10px;">Y= mX + b </td>

		    </tr>
		    <tr>
			<td colspan="4" align="left" style="padding: 10px;">Acceptance criteria:
			    r ≥ 0.9900
			</td>

		    </tr>

		    <tr>
			<td colspan="4" align="right" style="padding: 10px;">Fecha y hora de impresión</td>

		    </tr>
		</table>

		</body>
		</html>
