<?php
//header('Content-Disposition: attachment; filename="prueba.xls";');
//header('Content-Type: application/vnd.ms-excel');
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
	<div class="table-container">

	    <table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding:10px 0 0 0;">
		<tr>
		    <td width="238" align="left" height="20"  style="text-aling:justify;">

			Study No:
		    </td>
		    <td width="205" height="20" style="">

		    </td>


		</tr>
		<tr>
		    <td width="238" align="left" height="20"  align="center" style="padding:10px 0 0 0;">
			Table
		    </td>
		</tr>
		<tr>

		    <td width="238" colspan="2" align="left" height="20"  style="padding:10px 0 0 0;">
			<strong>Back-Calculated Concentration of Calibration Standards</strong>
		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 0 0 0">

			Analyte:
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 00 0">

			Biological Matrix
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 00 0">

			Concentration Units:
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>
	    </table>

	    <div class="cler"></div>
	    <div class="table-row">

		<table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff,margin-top:10px;text-aling:center;">
		    <tr>
			<td  colspan="4" align="center"></td>
		    </tr>
		    <tr>
			<td  align="center"  style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;"><strong>Calibration Standards</strong> </td>
			<td  align="center"  style=" border: black 1px solid;padding:2px">CS1</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px">CS2</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px">CS3</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px">CS4</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px">CS5</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px">CS6</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px">CS7</td>
			<td  align="center"   style=" border: black 1px solid;padding:2px;font-style:bold;">CS8</td>
		    </tr>
		    <tr>
			<td  align="center"  bgcolor="#B7CCE3" style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;"><strong>Nominal Concentrations</strong> </td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"   bgcolor="#B7CCE3" style=" border: black 1px solid;padding:2px"></td>


		    </tr>
		    <tr>
			<td colspan="9" align="left" style="border: black 1px solid;padding:2px"></td>

		    </tr>
		</table>
		<table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff,margin-top:10px;text-aling:center;">
		    <tr>
			<td  align="center"  colspan="3" style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;"><strong>Batch Results Table No.</strong> </td>
			<td  align="center" colspan="17" style=" border: black 1px solid;padding:2px">Back-Calculated Concentrations (5)</td>
		    </tr>
		    <tr>
			<td  align="center" bgcolor="#B7CCE3" colspan="3" style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;"><strong></strong> </td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
			<td  align="center"  style=" border: black 1px solid;padding:2px"></td>
		    </tr>





		</table>


		<tr>
		    <td colspan="4" align="right" style="padding: 10px;">Fecha y hora de impresión</td>

		</tr>
		</table>

		</body>
		</html>
