<?php
header('Content-Disposition: attachment; filename="prueba.xls";');
header('Content-Type: application/vnd.ms-excel');
//
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
	<div class="table-container">

	    <table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding:10px 0 0 0;">
		<tr>
		    <td width="238" align="left" height="20">

			Study No:
		    </td>
		    <td width="205" height="20" style="">

		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding:10px 0 0 0;">
			Table
		    </td>
		</tr>
		<tr>

		    <td width="238" colspan="2" align="left" height="20"  style="padding:10px 0 0 0;">
			<strong> Between-Run Accuracy and Precision of Quality Control Sample</strong>
		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 0 0 0">

			Analyte:
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 00 0">

			Biological Matrix
		    </td>
		    <td width="205" height="20" style="">

		    </td>

		</tr>

	    </table>

	    <div class="cler"></div>
	    <div class="table-row">

		<table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center;">
		    <tr>
			<td  colspan="2" align="center"></td>
		    </tr>
		    <tr>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:10px;font-size: 11px"><strong>Batch Results Table No></strong></td>
			<td  align="center" bgcolor="#91CCDB" colspan="9" style=" border: black 1px solid;padding:10px;font-size: 11px"><strong>BLDQC 695.80 ng/Ml</strong></td>
		    </tr>
		    <tr>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">Concentration Found</td>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">Dilution Factor</td>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> % Nominal (accuracy)</td>
		    </tr>
		    <tr>

			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="2" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center"  bgcolor="#F1DADA" colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>

		    </tr>
		    <tr>

			<td  align="center"  colspan="12" style=" border: black 1px solid;padding:5px;font-size: 11px"></td>
		    </tr>
		    <tr>

			<td  align="center" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"><strong>N</strong></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="2" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center"   colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>

		    </tr>
		    <tr>

			<td  align="center" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"><strong>Mean</strong></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="2" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center"   colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>

		    </tr>
		    <tr>

			<td  align="center" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"><strong>SD (±) </strong></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="2" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center"   colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>

		    </tr>
		    <tr>

			<td  align="center" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"><strong>CV (%)</strong></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center" bgcolor="#B5DCE7" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center" bgcolor="#B5DCE7" colspan="2" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>
			<td  align="center"   colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px"> </td>

		    </tr>



		    <tr>
			<td colspan="20" align="left" style="padding: 10px 0 2px 0;">Acceptance criteria: </td>
		    </tr>
		    <tr>
			<td colspan="20" align="left" style="padding: wpx;">For each DQC level, at least 2 of 3 must be 100 ± 15% nominal values for each analytical batch </td>
		    </tr>
		    <tr>
			<td colspan="20" align="left" style="padding: 2px;">RCS: Rejected Calibration Standard</td>
		    </tr>

		</table>
	    </div>
	</div>
    </body>
</html>
