<?php
header('Content-Disposition: attachment; filename="'. $filename .'.xls";');
header('Content-Type: application/vnd.ms-excel;charset=utf-8');
?>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="UTF-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>Pat Willener</o:Author>
  <o:Company>Good Day Books</o:Company>
 </o:DocumentProperties>
 <o:OfficeDocumentSettings>
  <o:RelyOnVML/>
  <o:AllowPNG/>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
<style>
<!--
@page
	{mso-page-orientation:landscape;}

-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Between_Run_Accuracy_and_Precision_of_dilution_Quality_Control_Samples</x:Name>
    <x:WorksheetOptions>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>1</x:Number>
       <x:ActiveRow>1</x:ActiveRow>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>8835</x:WindowHeight>
  <x:WindowWidth>15180</x:WindowWidth>
  <x:WindowTopX>120</x:WindowTopX>
  <x:WindowTopY>105</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->

<title></title>
</head>
<body>
<div class="Section1">
	<div class="table-container">
	    <table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding:10px 0 0 0;">
		<tr>
		    <td width="238" align="left" height="20">
			Study No:
		    </td>
		    <td width="205" height="20" style="">
                        <?php echo $analyte->getFkStudy()->getCode(); ?>
		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding:10px 0 0 0;">
			Table
		    </td>
		</tr>
		<tr>
		    <td width="238" colspan="2" align="left" height="20"  style="padding:10px 0 0 0;">
			<strong>Between-Run Accuracy and Precision of Dilution Quality Control Samples </strong>
		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 0 0 0">
			Analyte:
		    </td>
		    <td width="205" height="20" style="">
                        <?php echo $analyte->getFkAnalyte()->getName(); ?>
		    </td>
		</tr>
		<tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 00 0">
			Biological Matrix
		    </td>
		    <td width="205" height="20" style="">

		    </td>
		</tr>
                <tr>
		    <td width="238" align="left" height="20"  style="padding: 10px 00 0">
			Concentration Units:
		    </td>
		    <td width="205" height="20" style="">
                        <?php echo $analyte->getFkUnit()->getName(); ?>
		    </td>
		</tr>
	    </table>
	    <div class="cler"></div>
	    <div class="table-row">
		<table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center;">
		    <tr>
			<td  colspan="2" align="center"></td>
		    </tr>
		    <tr>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:10px;font-size: 11px"><strong>Batch Results Table No></strong></td>
			<td  align="center" bgcolor="" colspan="9" style=" border: black 1px solid;padding:10px;font-size: 11px">
                            <strong>LDQC</strong>
                        </td>
		    </tr>
		    <tr>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"></td>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">Concentration Found</td>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">Dilution Factor</td>
			<td  align="center"  colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px"> % Nominal (accuracy)</td>
		    </tr>
                    <?php foreach($list as $list) : ?>
		    <tr>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <strong>'<?php echo $list['name']; ?></strong>
                        </td>
			<?php foreach ($list['par'] as $key => $value) : ?>
                        <td  align="center"  bgcolor="" colspan="2"  style=" border: black 1px solid;padding:2px">
                            <?php echo ($value[2] != "" && $value[2] != "0") ? "NRV" : $value[0]; ?>
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $value[1]; ?>
                        </td>
                        <td  align="center"  bgcolor="" colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $value[2]; ?>
                        </td>
                        <?php endforeach; ?>
		    </tr>
                    <tr>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <strong></strong>
                        </td>
			<?php foreach ($list['impar'] as $key => $value) : ?>
                        <td  align="center"  bgcolor="" colspan="2"  style=" border: black 1px solid;padding:2px">
                            <?php echo ($value[2] != "" && $value[2] != "0") ? "NRV" : $value[0]; ?>
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $value[1]; ?>
                        </td>
                        <td  align="center"  bgcolor="" colspan="1" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $value[2]; ?>
                        </td>
                        <?php endforeach; ?>
		    </tr>
                    <?php endforeach; ?>
		    <tr>
			<td  align="center"  colspan="12" style=" border: black 1px solid;padding:5px;font-size: 11px"></td>
		    </tr>
                    <tr>
			<td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <strong>N</strong>
                        </td>
			<?php foreach ($calculations as $calculation) : ?>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $calculation['count']; ?>
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            N/AP
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $calculation['count']; ?>
                        </td>
                        <?php endforeach; ?>
		    </tr>
		    <tr>
                        <td  align="center"   colspan="2"  style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;">
                            <strong>Mean</strong>
                        </td>
			<?php foreach ($calculations as $calculation) : ?>
                        <td style= "mso-number-format:'#,##0.00';" align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $calculation['prom']; ?>
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            N/AP
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            <?php echo $calculation['accu']; ?>
                        </td>
                        <?php endforeach; ?>
		    </tr>
		    <tr>
			<td  style= "mso-number-format:'#,##0.0000';" align="center"   colspan="2"  style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;">
                            <strong>SD (±) </strong>
                        </td>
			<?php foreach ($calculations as $calculation) : ?>
                        <td style= "mso-number-format:'#,##0.0000';" align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            =DESVEST(<?php echo $calculation['values']; ?>)
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            N/AP
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">

                        </td>
                        <?php endforeach; ?>
		    </tr>
		    <tr>
			<td  align="center"   colspan="2"  style="color:#000; border: black 1px solid;font-size:14px;padding:10px;font-style:bold;">
                            <strong>CV (%)</strong>
                        </td>
			<?php foreach ($calculations as $calculation) : ?>
                        <td style= "mso-number-format:'#,##0.00';" align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            =DESVEST(<?php echo $calculation['values']; ?>)/PROMEDIO(<?php echo $calculation['values']; ?>)
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">
                            N/AP
                        </td>
                        <td  align="center" bgcolor="" colspan="3" style=" border: black 1px solid;padding:2px;font-size: 11px">

                        </td>
                        <?php endforeach; ?>
		    </tr>
		    <tr>
			<td colspan="20" align="left" style="padding: 10px 0 2px 0;">Acceptance criteria: </td>
		    </tr>
		    <tr>
			<td colspan="20" align="left" style="padding: wpx;">For each DQC level, at least 2 of 3 must be 100 ± 15% nominal values for each analytical batch </td>
		    </tr>
		    <tr>
			<td colspan="20" align="left" style="padding: 2px;">RCS: Rejected Calibration Standard</td>
		    </tr>

		</table>
	    </div>
	</div>
      </div>
    </body>
</html>
