<script type="text/javascript" src="<?php echo $this->basePath() ?>/js/datatable.js"></script>
<div id="logo">
    <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
</div>
<div id="cerrar">
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/study/index' ?>">cerrar ficha</a>]
</div>
<div id="cuerpo" style="height:77%;">
    <div id="create-study">
        <div id="encab">
            <h2>ficha del estudio</h2>
        </div>
        <div id="top" style="font-size:0.85em;">
            <ul id="errorBox"><?php echo isset($error) ? $error : ""?></ul>
            <form action="" method="post" id="paso1">
                <input type="hidden" name="op" value="paso1">
                <input type="hidden" name="studyMig" id="studyMig" value="">
                <input type="hidden" name="studyCode" id="studyCode" value="">
            </form>
            <form  id="migracion" action="" method="post" >
                <input type="hidden" name="op" value="migracion">
                <input type="hidden" name="studyMig2" id="studyMig2" value="<?php echo $studyMig; ?>">
                <input type="hidden" name="studyCode2" id="studyCode2" value="<?php echo $studyCode; ?>">
                <input type="hidden" name="dilutionTree2" id="dilutionTree2" value="">
            </form>
            <form id="study-form" action="" method="POST">
                <input type="hidden" name="op" value="normal">
                <p>
                    <label>Código:</label>
                    <input type="text" name="code" id="code" value="<?php echo $studyCode; ?>">
                </p>
                <p>
                    <label>Estudio a migrar:</label>
                    <?php echo $studyList; ?>
                    <a onclick="studyImportPrev();"><img title="migrar árboles de dilución" src="<?php echo $this->basePath() ?>/img/add.png"></a>
                    <label>Arbol de Dilución:</label>
                    <?php echo $dilutionTreeList; ?>
                    <?php echo $dilutionTreeListB; ?>
                    <?php echo $studyImportButton; ?>
                </p>
                <p>
                    <label id="labelfcreacion" name="labelfcreacion">Fecha creación:</label>
                    <input class="centro" type="date" id="create_at" name="create_at" value="<?php echo date("Y-m-d"); ?>">
                </p>
                <p>
                    <label id="labeldesc" name="labeldesc">Descripción:</label>
                    <textarea id="description" name="description" rows="2" cols="50"></textarea>
                </p>
                <p>
                    <label id="labelobs" name="labelobs">Observaciones:</label>
                    <textarea id="observation" name="observation" rows="2" cols="50"></textarea>
                </p>
                <ul>
                    <?php if ($user->isAdministrador() || $user->isDirectorEstudio()) : ?>
                        <li>
                            <input type="submit" id="studySave" name="studySave" class="btn" value="guardar" />
                        </li>
                    <?php endif; ?>
                </ul>
            </form>
        </div>
    </div>
    <div>
        <p>Pasos para realizar la migración</p>
        <p>1) Escribir el código del estudio.</p>
        <p>2) Si no se requiere migrar el estudio de ACUA se elige "Ninguno", se continúa con el proceso normal.</p>
        <p>3) Si se elige un estudio, se presiona el botón (+) y se migrarán los arboles de dilución de dicho estudio.</p>
        <p>4) Una vez que se seleccione el árbol de dilución se presiona el botón (+) y el proceso de migración quedará finalizado.</p>
    </div>
</div>
<script>
    jQuery.validator.addMethod("regex", function (value, element, params) {
        return this.optional(element) || /^[A-Z0-9]+(\-[0-9]+)?$/.test(value);
    }, "Please enter a valid Rule");
    $("#study-form").validate({
        rules: {
            code: {
                required: true,
                regex: true
            },
            create_at: {
                required: true
            },
            description: {
                required: true
            },
            observation: {
                required: true
            }
        },
        messages: {
            code: {
                required: "<strong>Código</strong> es requerido",
                regex: "Por favor, introduzca un <strong>Código</strong> válido. Ejm: XXANE-YYYY"
            },
            create_at: {
                required: "<strong>Fecha creación</strong> es requerido"
            },
            description: {
                required: "<strong>Descripción</strong> es requerido"
            },
            observation: {
                required: "<strong>Observaciones</strong> es requerido"
            }
        },
        errorLabelContainer: "#errorBox",
        wrapper: "li",
        submitHandler: function(form){
            answer = confirm("¿Desea guardar los cambios?");
            if (answer === true){
                form.submit();
                return true;
            }
            else{
                return false;
            }
        }
    });
</script>
<script>
    $('#studySave').hide("slow");
    $('#labelfcreacion').hide("slow");
    $('#create_at').hide("slow");
    $('#labeldesc').hide("slow");
    $('#description').hide("slow");
    $('#labelobs').hide("slow");
    $('#observation').hide("slow");
</script>