<div>
    <div id="encab">
        <h2><?php echo $AnaStudy->getFkStudy()->getCode(); ?></h2>
    </div>
    <form id="nominalconcentration-form" action="" method="POST">
        <div id="top">
            <ul>
                <li>
                    <!-- Guardar Perfil Laboratorio, Director de Estudio y Administrador -->
                    <input type="submit" class="btn" value="guardar" />
                </li>
                <?php if ($AnaStudy->getStatus()) : ?>
                    <li>
                        <!-- Validar Perfil Director de Estudio y Administrador -->
                                <button id="desbloquear" class="btn" type="button"><img src="img/unlock.png">desbloquear</button>
                        </li>
                <?php else : ?>
                    <li>
                        <!-- Desbloquear Perfil  Administrador -->
                                <button id="validar" class="btn" type="button"><img src="img/validar.png"> aprobar</button>
                        </li>
                    <li>
                        <p>aprobado por: Nombre Usuario (Director de Estudio). dd/mmm/aaaa hh:mm</p>
                    </li>
                <?php endif; ?>
            </ul>
            <p>Arbol de Dilución: (1)</p>
        </div>
        <div id="contenedor">
            <h5>Analito: <?php echo $AnaStudy->getFkAnalyte()->getName(); ?> (<?php echo $AnaStudy->getFkAnalyte()->getShortening(); ?>)</h5><br>
            <h4>Concentración Nominal de los Estándares de Calibración</h4>
            <ul>
                <?php for ($i = 0; $i < $AnaStudy->getCsNumber(); $i++) : ?>
                    <li>
                        <label>CS<?php echo $i + 1; ?>*</label>
                        <input type="text" value="<?php echo isset($cs_number[$i]) ? $cs_number[$i] : ""; ?>" name="cs_number[<?php echo $i; ?>]" class="nominalconcentration-form-number"/>
                    </li>
                <?php endfor; ?>
            </ul>
            <h4>Concentración Nominal de los Controles de Calidad</h4>
            <ul>
                <?php for ($i = 0; $i < $AnaStudy->getQcNumber(); $i++) : ?>
                    <li>
                        <label>QC<?php echo $i + 1; ?>*</label>
                        <input type="text" value="<?php echo isset($qc_number[$i]) ? $qc_number[$i] : ""; ?>" name="qc_number[<?php echo $i; ?>]" class="nominalconcentration-form-number"/>
                    </li>
                <?php endfor; ?>
            </ul>
        </div>
        <input type="hidden" name="id" value="<?php echo $AnaStudy->getPkAnalyteStudy(); ?>" />
    </form>
    <script>
        jQuery.validator.addMethod("regex", function(value, element, params) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:,\d{3})+)?(?:\.\d+)?$/.test(value);
        }, "Please enter a valid number");
        jQuery.validator.addClassRules('nominalconcentration-form-number', {
            required: true,
            regex: true
        });
        $("#nominalconcentration-form").validate();
    </script>
</div>