<body>
    <div id="cerrar"><a href="index.html"><img title="regresar a la pantalla de login" src="img/close.png"></a></div>
    <div id="principal">
	<div id="cuerpo">
	    <div id="central">
		<a href="../alae.html"><img src="img/alaelogo.png" width="300px"></a>
		<div id="login">
		    <h1>Indique su contraseña</h1>
		    <form>
			<table>
			    <?php echo $pass ?>
			    <?php echo $usr ?>
			    <tbody><tr><td>Nombre de usuario:</td>
				    <td>[Nombre de usuario]</td></tr>
				<tr><td>Contraseña (*):</td>
				    <td><input type="password" id="pwd"></td></tr>
				<tr><td>Confirmar contraseña (*):</td>
				    <td><input type="password" id="repwd"></td></tr>
				<tr><td>Correo electrónico:</td>
				    <td>[correo@anapharmeurope.com]</td></tr>
				<tr><td>Nombre real (*):</td>
				    <td><input type="text" id="nom"></td></tr>
				<tr><td>
					<p class="peq" style="color:#f00">(*) Requerido</p></td>
				    <td><a href="#">
					    <input type="button" value="Actualizar usuario" id="enviar"></a>
				    </td></tr>
				<tr><td colspan="2">
					<p class="peq" style="line-height:1.3em;">
					    El acceso a ALAE requiere de aprobación.<br>
					    Una vez que el Administrador de la Aplicación le asigne su perfil, <br>podrá tener acceso a ALAE con el nombre de usuario y la contraseña indicados.<br>
					</p></td></tr>
			    </tbody></table>
		    </form>
		</div>
	    </div>
	</div>
	<div id="pie">
	    <p><a href="./help/alaeIndex.pdf" target="blank"><img src="./img/help.png" title="ayuda sobre esta pantalla"></a>
		Ayuda sobre el Sistema</p>
	    <p><a href="./sf/alae001sf.pdf" target="blank"><img src="./img/info.png" title="Especificaciones funcionales"></a>
		ALAE Software. Copyright © Anapharm, 2013.</p>
	</div>
    </div>

</body>