<div id="cerrar">
    <a href="index.html"><img title="regresar a la pantalla de login" src="<?php echo $this->basePath(); ?>/img/close.png"/></a></div>
<div id="principal">
    <div id="cuerpo">
	<div id="central">
	    <a href="../alae.html"><img src=" <?php echo $this->basePath(); ?>/img/alaelogo.png" width="400px"/></a>
	    <div id="login">
		<h1>Solicitar acceso a ALAE</h1>
		<form method="POST"  id="newaccount" action="<?php echo $this->url('user', array('action' => 'newaccount')); ?>">
		    <table>
			<tr><td><label for="username">Nombre de usuario:</td>
			    <td><input id="username" name="username" type="text" ></tr>
			<tr>
			<tr>
			    <td>
				<?php
				if (!empty($error['usr']))
				{
				    echo "<td><label class='error' id='usrerrorlabel'>" . $error['usr'] . "</label></td>";
				}
				?>
			    </td>
			</tr>
			<tr><td><label for="email"> Correo electrónico:</td>
			    <td><input id="email" type="email" name="email"></td></tr>

			<tr>
			    <td>
				<?php
				if (!empty($error['email']))
				{
				    echo "<tr><td></td><td><label class='error' id='erroremail'>" . $error['email'] . "</label></td></tr>";
				}
				?>
			    </td>
			</tr>



			<tr><td>[ <a href="index.html">Inicio de sesi&oacute;n</a> ]</td>

			    <td>
				<a href="alae001m.html" target="blank">
				    <input type="submit" value="Enviar" id="enviar">
				</a>
			    </td>
			</tr>
			<tr><td colspan="2">
				<p class="peq" style="line-height:1.3em;">Le enviaremos un correo electrónico de confirmación a la dirección especificada.<br/>
				    Usando ese mensaje de correo electrónico podrá solicitar su cuenta. <br/>
				    Si esta solicitud no se efectúa en siete días, la misma ser&aacute; ignorada.<br/>
				    Debe ingresar una dirección de correo electrónico <strong>anapharmeurope</strong>
				    para poder recibir el mensaje de verificación. </p>
			    </td></tr>
		    </table>
		</form>
	    </div>
	</div>
    </div>
    <div id="pie">
	<p><a href="./help/alaeIndex.pdf" target="blank"><img src="<?php echo $this->basePath(); ?>/img/help.png"  title="ayuda sobre esta pantalla" /></a>
	    Ayuda sobre el Sistema</p>
	<p><a href="./sf/alae001sf.pdf" target="blank"><img src="<?php echo $this->basePath(); ?>/img/info.png"  title="Especificaciones funcionales" /></a>
	    ALAE Software. Copyright © Anapharm, 2013.</p>
    </div>
</div>
