<html>
    <div id="principal">
	<div id="cuerpo">
	    <div id="central">
		<a href="<?php echo $this->url('user', array('action' => 'resetpass')); ?>">
		    <img src="<?php echo $this->basePath() . '/img/alaelogo.png' ?> "/></a>
		<div id="login">
		    <h1>Reinicializar contraseña  </h1>
		    <?php
		    echo "<div>" . $message . "<div>";
		    ?>
		    <form method="POST"  id="resetpass" action="<?php echo $this->url('user', array('action' => 'resetpass')); ?>">
			<table>
			    <tbody><tr><td>Nombre de usuario:</td>
				    <td><input type="text" id="username" name="username"></td></tr>
				<!-- para efectos de demostración, cambiar por SUBMIT  el botón a continuación-->
				<tr><td>[ <a href="index.html">Inicio de sesión</a> ]</td>
				    <td><a href="#"><input type="submit" value="Enviar" id="sentmailrpass"></a></td></tr>
				<tr><td colspan="2">
					<p class="peq" style="line-height:1.3em;">Recibirá por correo electrónico una dirección especial para cambiar su contraseña,<br>
					    que contiene un código de validación para su cuenta. <br>
					    Por favor siga las instrucciones que recibirá para cambiar su contraseña. </p>
				    </td></tr>
			    </tbody></table>
		    </form>
		</div>
	    </div>
	</div>
	<div id="pie">
	    <p><a href="./help/alaeIndex.pdf" target="blank"><img src="./img/help.png" title="ayuda sobre esta pantalla"></a>
		Ayuda sobre el Sistema</p>
	    <p><a href="./sf/alae001sf.pdf" target="blank"><img src="./img/info.png" title="Especificaciones funcionales"></a>
		ALAE Software. Copyright © Anapharm, 2013.</p>
	</div>
    </div>


