<head>
    <title>ALAE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

    <link rel="shortcut icon" href="img/favicon.ico">
</head>
<body>
    <div id="principal">
	<div id="cuerpo">
	    <a href="../alae.html"><img src="img/alaelogo.png"></a>
	    <div id="central" style="text-align:left; font-size:1.1em;">
		<hr/>
		<blockquote>
		    <p> Su Código de verificacin es :<?php echo $verification ?></p>
		    <blockquote>

			<span class="peq"></span>
		    </blockquote>
		    <p>Si usted no solicit&oacute; el c&oacute;digo, ignore este mensaje.</p>
		</blockquote>
	    </div>
	</div>

    </div>
</body>
</html>