<head>
    <title>ALAE</title>
    <style type="text/css" media="Screen"> /*\*/@import url("./css/alae.css");/**/ </style>
    <link rel="shortcut icon" href="img/favicon.ico">
</head>
<body>
    <div id="principal">
	<div id="cuerpo">
	    <a href="../alae.html"><img src="img/alaelogo.png" width="400px"/></a>
	    <div id="central" style="text-align:left; font-size:1.1em;">
		<h4>Mail que le llegar&aacute; al nuevo usuario</h4>
		<p><label>De:</label>Administrador de ALAE</p>
		<p><label>Para:</label>[nombre de usuario] [correo@anapharmeurope.com]</p>
		<p><label>Asunto:</label>Solicitud de Acceso a ALAE</p>
		<hr/>
		<blockquote>
		    <p>Ha solicitado una cuenta en ALAE con el nombre de usuario: <br/>
			<strong><?php echo $user; ?></strong>. </p>
		    <p>Para completar el registro, <br/>
			visite la siguiente URL e ingrese la contraseña que desee:</p>
		    <a href="http://localhost/alae/public/user/confirmnewaccount?usr=   <?php echo $user; ?> &pass= <?php echo $password; ?>  ">formulario para indicar la contraseña. clicar aquí</a>;
		    <blockquote>

			<span class="peq">(formulario para indicar la contrase&ntilde;a. clica)</span>
			<span class="peq">
			</span>
		    </blockquote>

		    <p>Si usted no solicitó el registro, ignore este mensaje.</p></blockquote>
	    </div>
	</div>

    </div>
</body>
</html>