<head>
    <title>ALAE</title>
    <style type="text/css" media="Screen"> /*\*/@import url("./css/alae.css");/**/ </style>
    <link rel="shortcut icon" href="img/favicon.ico">
</head>
<body>
    <div id="principal">
	<div id="cuerpo">
	    <a href="../alae.html"><img src="img/alaelogo.png" width="400px"/></a>
	    <div id="central" style="text-align:left; font-size:1.1em;">
		<hr/>
		<blockquote>
		    El Usuario <?php echo $user; ?> ha solicitado acceso al sistema Alae;
		</blockquote>
	    </div>
	</div>

    </div>
</body>
</html>